"""add user_id column in comment table

Revision ID: 506339afc6dc
Revises: aa5b3751eb27
Create Date: 2022-02-06 06:57:10.759904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506339afc6dc'
down_revision = 'aa5b3751eb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
