"""add votes model

Revision ID: aa5b3751eb27
Revises: 32986e804c51
Create Date: 2022-02-06 06:21:57.780939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5b3751eb27'
down_revision = '32986e804c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voted_on', sa.DateTime(), nullable=True),
    sa.Column('downvote', sa.Boolean(), nullable=True),
    sa.Column('upvote', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('comments_category_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'category_id')
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'pitch_date')
    op.drop_column('pitches', 'category_id')
    op.add_column('comments', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_category_id_fkey', 'comments', 'categories', ['category_id'], ['id'])
    op.drop_table('votes')
    # ### end Alembic commands ###
