"""update the pitch table with the content column

Revision ID: b9faf42fcb60
Revises: 506339afc6dc
Create Date: 2022-02-06 20:05:15.979856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9faf42fcb60'
down_revision = '506339afc6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###
